const gcodes = [
  // ----- G-CODES -----
  { code: "G0", desc: "Linearer Eilgang: Schnelle Positionierung", params: true, example: "X100 Y100 Z5 F3000" },
  { code: "G1", desc: "Lineare Bewegung: Standard-Fahrt mit Vorschub", params: true, example: "X50 Y20 Z-1.2 F1000" },
  { code: "G2", desc: "Bogen im Uhrzeigersinn", params: true, example: "X10 Y10 I5 J0" },
  { code: "G3", desc: "Bogen gegen den Uhrzeigersinn", params: true, example: "X10 Y10 I5 J0" },
  { code: "G4", desc: "Verweilzeit / Pause", params: true, example: "S2" },
  { code: "G5", desc: "Bézier-Spline-Bewegung", params: true, example: "X50 Y50 I10 J0 P5 Q0" },
  { code: "G6", desc: "Direkter Stepper-Move (nicht kinematisch)", params: true, example: "X10 Y-10 Z5" },
  { code: "G10", desc: "Retract: Filament zurückziehen", params: false },
  { code: "G11", desc: "Recover: Retract rückgängig machen", params: false },
  { code: "G12", desc: "Düse reinigen", params: true, example: "P1" },
  { code: "G17", desc: "CNC-Ebene XY wählen", params: false },
  { code: "G18", desc: "CNC-Ebene ZX wählen", params: false },
  { code: "G19", desc: "CNC-Ebene YZ wählen", params: false },
  { code: "G20", desc: "Einheiten auf Zoll", params: false },
  { code: "G21", desc: "Einheiten auf Millimeter", params: false },
  { code: "G26", desc: "Mesh-Testmuster drucken", params: false },
  { code: "G27", desc: "Druckkopf parken", params: false },
  { code: "G28", desc: "Auto-Home: Achsen referenzieren", params: true, example: "X Y Z" },
  { code: "G29", desc: "Bett-Nivellierung (verschiedene Modi)", params: false },
  { code: "G30", desc: "Einzelner Z-Probe-Messpunkt", params: false },
  { code: "G31", desc: "Dock Sled: Probe-Schlitten andocken", params: false },
  { code: "G32", desc: "Undock Sled: Probe-Schlitten lösen", params: false },
  { code: "G33", desc: "Delta Auto-Kalibrierung", params: false },
  { code: "G34", desc: "Z-Gantry/Steppers auto ausrichten", params: false },
  { code: "G35", desc: "Tramming-Assistent für Bett", params: false },
  { code: "G38.2", desc: "Probing in Richtung Werkstück", params: true, example: "Z-10 F100" },
  { code: "G38.3", desc: "Probing ohne Fehler bei Fehlschlag", params: true, example: "Z-10 F100" },
  { code: "G38.4", desc: "Probing vom Werkstück weg", params: true, example: "Z10 F100" },
  { code: "G38.5", desc: "Probing weg ohne Fehler bei Fehlschlag", params: true, example: "Z10 F100" },
  { code: "G42", desc: "Zu Mesh-Koordinate fahren", params: true, example: "I3 J3" },
  { code: "G53", desc: "Bewegung in Maschinenkoordinaten", params: true, example: "G0 X0 Y0 Z0" },
  { code: "G54", desc: "Workspace-Koordinatensystem 1 wählen", params: false },
  { code: "G55", desc: "Workspace-Koordinatensystem 2 wählen", params: false },
  { code: "G56", desc: "Workspace-Koordinatensystem 3 wählen", params: false },
  { code: "G57", desc: "Workspace-Koordinatensystem 4 wählen", params: false },
  { code: "G58", desc: "Workspace-Koordinatensystem 5 wählen", params: false },
  { code: "G59", desc: "Workspace-Koordinatensystem 6 wählen", params: false },
  { code: "G59.1", desc: "Workspace G59.1 wählen", params: false },
  { code: "G59.2", desc: "Workspace G59.2 wählen", params: false },
  { code: "G59.3", desc: "Workspace G59.3 wählen", params: false },
  { code: "G60", desc: "Position(en) speichern", params: true, example: "S0" },
  { code: "G61", desc: "Zu gespeicherter Position zurückkehren", params: true, example: "S0" },
  { code: "G76", desc: "Sensor-Temperatur-Kalibrierung für Probe", params: false },
  { code: "G80", desc: "Aktuellen Bewegungsmodus abbrechen", params: false },
  { code: "G90", desc: "Absolute Positionierung aktivieren", params: false },
  { code: "G91", desc: "Relative Positionierung aktivieren", params: false },
  { code: "G92", desc: "Aktuelle Position setzen", params: true, example: "X0 Y0 Z0" },
  { code: "G425", desc: "Backlash-Kalibrierung mit leitfähigem Block", params: false },

  // ----- M-CODES -----
  { code: "M0", desc: "Unbedingter Stopp, auf Benutzer warten", params: false },
  { code: "M1", desc: "Pause / Stopp (optional)", params: false },
  { code: "M3", desc: "Spindel CW / Laser an", params: true, example: "S255" },
  { code: "M4", desc: "Spindel CCW / Laser an", params: true, example: "S255" },
  { code: "M5", desc: "Spindel / Laser aus", params: false },
  { code: "M7", desc: "Kühlmittel (Mist) ein", params: false },
  { code: "M8", desc: "Kühlmittel (Flood) ein", params: false },
  { code: "M9", desc: "Kühlmittel aus", params: false },
  { code: "M10", desc: "Vakuum / Blower an", params: false },
  { code: "M11", desc: "Vakuum / Blower aus", params: false },
  { code: "M16", desc: "Drucker-Check: G-Code für Maschine prüfen", params: false },
  { code: "M17", desc: "Stepper aktivieren", params: false },
  { code: "M18", desc: "Stepper deaktivieren", params: false },
  { code: "M20", desc: "SD-Karteninhalt auflisten", params: false },
  { code: "M21", desc: "SD-Karte initialisieren", params: false },
  { code: "M22", desc: "SD-Karte auswerfen", params: false },
  { code: "M23", desc: "SD-Datei auswählen", params: true, example: "test.gcode" },
  { code: "M24", desc: "SD-Druck starten/fortsetzen", params: false },
  { code: "M25", desc: "SD-Druck pausieren", params: false },
  { code: "M26", desc: "SD-Leseposition setzen", params: true, example: "S1000" },
  { code: "M27", desc: "SD-Druckstatus melden", params: false },
  { code: "M28", desc: "SD-Datei zum Schreiben öffnen", params: true, example: "log.gcode" },
  { code: "M29", desc: "SD-Schreiben beenden", params: false },
  { code: "M30", desc: "SD-Datei löschen", params: true, example: "test.gcode" },
  { code: "M31", desc: "Druckzeit melden", params: false },
  { code: "M32", desc: "SD-Datei wählen und starten", params: true, example: "job.gcode" },
  { code: "M33", desc: "Langen Pfadnamen von SD holen", params: true, example: "SHORTNM~1.GCO" },
  { code: "M34", desc: "Sortierung der SD-Dateien einstellen", params: true, example: "S1" },
  { code: "M42", desc: "Pin-Zustand setzen", params: true, example: "P5 S255" },
  { code: "M43", desc: "Pins debuggen / testen", params: true, example: "P5" },
  { code: "M48", desc: "Probe-Wiederholgenauigkeit testen", params: true, example: "P10" },
  { code: "M73", desc: "Druckfortschritt setzen", params: true, example: "P50" },
  { code: "M75", desc: "Job-Timer starten", params: false },
  { code: "M76", desc: "Job-Timer pausieren", params: false },
  { code: "M77", desc: "Job-Timer stoppen", params: false },
  { code: "M78", desc: "Job-Statistiken ausgeben", params: false },
  { code: "M80", desc: "Netzteil einschalten", params: false },
  { code: "M81", desc: "Netzteil ausschalten", params: false },
  { code: "M82", desc: "Extruder E absolut", params: false },
  { code: "M83", desc: "Extruder E relativ", params: false },
  { code: "M85", desc: "Inaktivitäts-Timeout setzen", params: true, example: "S600" },
  { code: "M86", desc: "Hotend-Idle-Timeout setzen", params: true, example: "S300" },
  { code: "M87", desc: "Hotend-Idle-Timeout deaktivieren", params: false },
  { code: "M92", desc: "Steps/mm für Achsen setzen", params: true, example: "X80 Y80 Z400 E95" },
  { code: "M100", desc: "Speicherverbrauch ausgeben", params: false },
  { code: "M102", desc: "Bettsensor-Distanz konfigurieren", params: false },
  { code: "M104", desc: "Hotend-Temperatur setzen", params: true, example: "S200" },
  { code: "M105", desc: "Temperaturen melden", params: false },
  { code: "M106", desc: "Lüftergeschwindigkeit setzen", params: true, example: "S128" },
  { code: "M107", desc: "Lüfter aus", params: false },
  { code: "M108", desc: "Warten abbrechen und fortsetzen", params: false },
  { code: "M109", desc: "Auf Hotend-Temperatur warten", params: true, example: "S200" },
  { code: "M110", desc: "Zeilennummer setzen/holen", params: true, example: "N1" },
  { code: "M111", desc: "Debug-Level setzen/anzeigen", params: true, example: "S1" },
  { code: "M112", desc: "Not-Aus / vollständiger Shutdown", params: false },
  { code: "M113", desc: "Host-Keepalive-Intervall setzen", params: true, example: "S2" },
  { code: "M114", desc: "Aktuelle Position melden", params: false },
  { code: "M115", desc: "Firmware-Info ausgeben", params: false },
  { code: "M117", desc: "LCD-Nachricht setzen", params: true, example: "Druck läuft" },
  { code: "M118", desc: "Text auf seriell ausgeben", params: true, example: "Hallo Host" },
  { code: "M119", desc: "Endstop-Status melden", params: false },
  { code: "M120", desc: "Endstops einschalten", params: false },
  { code: "M121", desc: "Endstops ausschalten", params: false },
  { code: "M122", desc: "TMC-Debug-Info", params: false },
  { code: "M123", desc: "Lüfter-Tachos melden", params: false },
  { code: "M125", desc: "Kopf parken (Filamentwechsel)", params: false },
  { code: "M126", desc: "Baricuda 1 Ventil öffnen", params: false },
  { code: "M127", desc: "Baricuda 1 Ventil schließen", params: false },
  { code: "M128", desc: "Baricuda 2 Ventil öffnen", params: false },
  { code: "M129", desc: "Baricuda 2 Ventil schließen", params: false },
  { code: "M140", desc: "Bett-Temperatur setzen", params: true, example: "S60" },
  { code: "M141", desc: "Kammer-Temperatur setzen", params: true, example: "S40" },
  { code: "M143", desc: "Laser-Kühler-Temperatur setzen", params: true, example: "S25" },
  { code: "M145", desc: "Material-Preset im LCD setzen", params: true, example: "S0 H200 B60 F0" },
  { code: "M149", desc: "Temperatureinheit setzen", params: true, example: "C" },
  { code: "M150", desc: "RGB(W)-LED-Farbe setzen", params: true, example: "R255 U255 B0" },
  { code: "M154", desc: "Positions-Autoreport", params: true, example: "S1" },
  { code: "M155", desc: "Temperatur-Autoreport", params: true, example: "S2" },
  { code: "M163", desc: "Mix-Faktor setzen", params: true, example: "S0 P1.0" },
  { code: "M164", desc: "Mix als Tool speichern", params: true, example: "S0" },
  { code: "M165", desc: "Alle Mix-Faktoren setzen", params: true, example: "A0.5 B0.5" },
  { code: "M166", desc: "Gradient-Mix setzen", params: true, example: "U1 V0" },
  { code: "M190", desc: "Auf Bett-Temperatur warten", params: true, example: "S60" },
  { code: "M191", desc: "Auf Kammer-Temperatur warten", params: true, example: "S40" },
  { code: "M192", desc: "Auf Probe-Temperatur warten", params: true, example: "S30" },
  { code: "M193", desc: "Auf Laser-Kühler-Temperatur warten", params: true, example: "S25" },
  { code: "M200", desc: "Volumetrischen Extrusionsdurchmesser setzen", params: true, example: "D1.75" },
  { code: "M201", desc: "Beschleunigungs-/Limitwerte setzen", params: true, example: "X1000 Y1000 Z100 E5000" },
  { code: "M203", desc: "Maximalvorschub setzen", params: true, example: "X300 Y300 Z5 E25" },
  { code: "M204", desc: "Startbeschleunigung nach Typ setzen", params: true, example: "P1000 T2000" },
  { code: "M205", desc: "Erweiterte Bewegungs-Parameter", params: true, example: "X10 Y10" },
  { code: "M206", desc: "Home-Offset setzen", params: true, example: "X0 Y0 Z0" },
  { code: "M207", desc: "Firmware-Retract-Einstellungen", params: true, example: "S2.0 F2400" },
  { code: "M208", desc: "Firmware-Recover-Einstellungen", params: true, example: "S0.0 F2400" },
  { code: "M209", desc: "Auto-Retract an/aus", params: true, example: "S1" },
  { code: "M210", desc: "Homing-Feedrate setzen", params: true, example: "X50 Y50 Z4" },
  { code: "M211", desc: "Software-Endstops setzen/anzeigen", params: true, example: "S1" },
  { code: "M217", desc: "Filament-Swap-Parameter", params: true, example: "S30" },
  { code: "M218", desc: "Hotend-Offset setzen", params: true, example: "T1 X0 Y20" },
  { code: "M220", desc: "Feedrate-Prozent setzen", params: true, example: "S120" },
  { code: "M221", desc: "Flow-Prozent setzen", params: true, example: "S95" },
  { code: "M226", desc: "Auf Pin-Zustand warten", params: true, example: "P5 S1" },
  { code: "M240", desc: "Kamera auslösen", params: false },
  { code: "M250", desc: "LCD-Kontrast setzen/lesen", params: true, example: "C10" },
  { code: "M255", desc: "LCD-Sleep-/Backlight-Timeout", params: true, example: "S30" },
  { code: "M256", desc: "LCD-Helligkeit", params: true, example: "B20" },
  { code: "M260", desc: "I2C-Senden", params: true, example: "A4 B1" },
  { code: "M261", desc: "I2C-Anfrage", params: true, example: "A4 B1" },
  { code: "M265", desc: "I2C-Bus scannen", params: false },
  { code: "M280", desc: "Servo-Position setzen/lesen", params: true, example: "P0 S90" },
  { code: "M281", desc: "Servo-Winkel bearbeiten", params: true, example: "P0 L10 U170" },
  { code: "M282", desc: "Servo lösen (detach)", params: true, example: "P0" },
  { code: "M290", desc: "Babystepping", params: true, example: "Z0.05" },
  { code: "M300", desc: "Ton / Beep abspielen", params: true, example: "S1000 P500" },
  { code: "M301", desc: "Hotend-PID setzen", params: true, example: "P22.2 I1.08 D114" },
  { code: "M302", desc: "Cold-Extrude erlauben / Limit setzen", params: true, example: "S0" },
  { code: "M303", desc: "PID-Autotune", params: true, example: "E0 S200 C8" },
  { code: "M304", desc: "Bett-PID setzen", params: true, example: "P400 I70 D600" },
  { code: "M305", desc: "Benutzer-Thermistor-Parameter", params: true, example: "P0 R4700" },
  { code: "M306", desc: "Model Predictive Temp-Control", params: true, example: "P0" },
  { code: "M309", desc: "Kammer-PID setzen", params: true, example: "P10 I0.5 D80" },
  { code: "M350", desc: "Mikroschritt-Einstellungen setzen", params: true, example: "X16 Y16 Z16 E16" },
  { code: "M351", desc: "Microstep-Pins direkt setzen", params: true, example: "X1" },
  { code: "M355", desc: "Gehäusebeleuchtung steuern", params: true, example: "S1 P255" },
  { code: "M360", desc: "SCARA Theta A fahren", params: false },
  { code: "M361", desc: "SCARA Theta B fahren", params: false },
  { code: "M362", desc: "SCARA Psi A fahren", params: false },
  { code: "M363", desc: "SCARA Psi B fahren", params: false },
  { code: "M364", desc: "SCARA Psi C fahren", params: false },
  { code: "M380", desc: "Solenoid aktivieren", params: false },
  { code: "M381", desc: "Alle Solenoids deaktivieren", params: false },
  { code: "M400", desc: "Auf Abschluss aller Moves warten", params: false },
  { code: "M401", desc: "Probe ausklappen", params: false },
  { code: "M402", desc: "Probe einklappen", params: false },
  { code: "M403", desc: "MMU2 Filament-Typ setzen", params: true, example: "E0 F1" },
  { code: "M404", desc: "Nominalen Filamentdurchmesser setzen", params: true, example: "N1.75" },
  { code: "M405", desc: "Filament-Sensor an", params: false },
  { code: "M406", desc: "Filament-Sensor aus", params: false },
  { code: "M407", desc: "Aktuelle Filamentbreite melden", params: false },
  { code: "M410", desc: "Quickstop: sofort alle Steppers stoppen", params: false },
  { code: "M412", desc: "Filament-Runout-Parameter setzen/lesen", params: true, example: "S1" },
  { code: "M413", desc: "Power-Loss-Recovery an/aus", params: true, example: "S1" },
  { code: "M414", desc: "LCD-Sprache setzen/lesen", params: true, example: "S1" },
  { code: "M420", desc: "Bett-Leveling-Status/Parameter", params: true, example: "S1" },
  { code: "M421", desc: "Einzelnen Mesh-Z-Wert setzen", params: true, example: "I3 J3 Z0.05" },
  { code: "M422", desc: "Z-Motor-XY für Auto-Alignment setzen", params: true, example: "S0 X10 Y10" },
  { code: "M423", desc: "X-Twist-Kompensation konfigurieren", params: true, example: "S0" },
  { code: "M425", desc: "Backlash-Kompensation konfigurieren", params: true, example: "F1" },
  { code: "M428", desc: "Home-Offests aus aktueller Position", params: false },
  { code: "M430", desc: "Power-Monitor (A/V/W) anzeigen", params: false },
  { code: "M486", desc: "Objekte identifizieren / abbrechen", params: true, example: "S1" },
  { code: "M493", desc: "Fixed-Time-Motion & Input-Shaping", params: true, example: "S1" },
  { code: "M494", desc: "FT-Motion-Trajectory-Smoothing", params: true, example: "S1" },
  { code: "M500", desc: "Einstellungen in EEPROM speichern", params: false },
  { code: "M501", desc: "Einstellungen aus EEPROM laden", params: false },
  { code: "M502", desc: "Werkseinstellungen laden", params: false },
  { code: "M503", desc: "Gespeicherte Einstellungen anzeigen", params: false },
  { code: "M504", desc: "EEPROM-Inhalt validieren", params: false },
  { code: "M510", desc: "Maschine sperren", params: false },
  { code: "M511", desc: "Maschine entsperren", params: false },
  { code: "M512", desc: "Passcode setzen", params: true, example: "P1234" },
  { code: "M524", desc: "SD-Druck abbrechen", params: false },
  { code: "M540", desc: "SD-Druck bei Endstop-Abbruch", params: true, example: "S1" },
  { code: "M550", desc: "Maschinennamen setzen/lesen", params: true, example: "MyPrinter" },
  { code: "M552", desc: "Ethernet-IP/Interface-Status", params: true, example: "P192.168.1.10" },
  { code: "M553", desc: "Ethernet-Subnet-Maske", params: true, example: "P255.255.255.0" },
  { code: "M554", desc: "Ethernet-Gateway-IP", params: true, example: "P192.168.1.1" },
  { code: "M569", desc: "TMC-Stepping-Modus / StealthChop", params: true, example: "S1" },
  { code: "M575", desc: "Serielle Baudrate anpassen", params: true, example: "P1 B250000" },
  { code: "M592", desc: "Nichtlineare Extrusion einstellen", params: true, example: "D0 A0.02" },
  { code: "M593", desc: "ZV-Input-Shaping-Parameter", params: true, example: "F40" },
  { code: "M600", desc: "Filamentwechsel automatisch", params: false },
  { code: "M603", desc: "Filamentwechsel-Parameter konfigurieren", params: true, example: "L50 U10" },
  { code: "M605", desc: "Multi-Nozzle-Modus setzen", params: true, example: "S2" },
  { code: "M665", desc: "Delta/SCARA-Geometrie setzen", params: true, example: "L215 R145" },
  { code: "M666", desc: "Dual-/Delta-Endstop-Offsets", params: true, example: "X0.1 Y-0.1" },
  { code: "M672", desc: "Duet Smart Effector Sensitivität", params: true, example: "S100" },
  { code: "M701", desc: "Filament laden", params: false },
  { code: "M702", desc: "Filament entladen", params: false },
  { code: "M710", desc: "Controller-Lüfter-Einstellungen", params: true, example: "S1" },
  { code: "M7219", desc: "MAX7219 LED-Segmente steuern", params: true, example: "S1" },
  { code: "M808", desc: "Repeat-Marker setzen/anspringen", params: true, example: "L5" },
  { code: "M810", desc: "G-Code-Makro 0 setzen/ausführen", params: true, example: "G28" },
  { code: "M811", desc: "G-Code-Makro 1 setzen/ausführen", params: true, example: "" },
  { code: "M812", desc: "G-Code-Makro 2 setzen/ausführen", params: true, example: "" },
  { code: "M813", desc: "G-Code-Makro 3 setzen/ausführen", params: true, example: "" },
  { code: "M814", desc: "G-Code-Makro 4 setzen/ausführen", params: true, example: "" },
  { code: "M815", desc: "G-Code-Makro 5 setzen/ausführen", params: true, example: "" },
  { code: "M816", desc: "G-Code-Makro 6 setzen/ausführen", params: true, example: "" },
  { code: "M817", desc: "G-Code-Makro 7 setzen/ausführen", params: true, example: "" },
  { code: "M818", desc: "G-Code-Makro 8 setzen/ausführen", params: true, example: "" },
  { code: "M819", desc: "G-Code-Makro 9 setzen/ausführen", params: true, example: "" },
  { code: "M820", desc: "Alle Makros auflisten", params: false },
  { code: "M851", desc: "Probe-Offset XYZ setzen", params: true, example: "X0 Y0 Z-1.5" },
  { code: "M852", desc: "Bett-Skew-Kompensation", params: true, example: "I0.01 J-0.01" },
  { code: "M860", desc: "I2C-Encoder Konfiguration", params: true, example: "S0" },
  { code: "M861", desc: "I2C-Encoder Slot 1", params: true, example: "S1" },
  { code: "M862", desc: "I2C-Encoder Slot 2", params: true, example: "S2" },
  { code: "M863", desc: "I2C-Encoder Slot 3", params: true, example: "S3" },
  { code: "M864", desc: "I2C-Encoder Slot 4", params: true, example: "S4" },
  { code: "M865", desc: "I2C-Encoder Slot 5", params: true, example: "S5" },
  { code: "M866", desc: "I2C-Encoder Slot 6", params: true, example: "S6" },
  { code: "M867", desc: "I2C-Encoder Slot 7", params: true, example: "S7" },
  { code: "M868", desc: "I2C-Encoder Slot 8", params: true, example: "S8" },
  { code: "M869", desc: "I2C-Encoder Status", params: true, example: "" },
  { code: "M871", desc: "Probe-Temperatur-Kompensation", params: true, example: "S1" },
  { code: "M876", desc: "Host-Prompt-Antwort verarbeiten", params: true, example: "S0" },
  { code: "M900", desc: "Linear Advance K-Faktor", params: true, example: "K0.05" },
  { code: "M906", desc: "Stepper-Motor-Strom setzen", params: true, example: "X800 Y800 Z800 E600" },
  { code: "M907", desc: "Trimpot-Motorstrom", params: true, example: "X800" },
  { code: "M908", desc: "Trimpot-Pins direkt setzen", params: true, example: "P0 S127" },
  { code: "M909", desc: "DAC-Stepper-Strom melden", params: false },
  { code: "M910", desc: "DAC-Werte in EEPROM sichern", params: false },
  { code: "M911", desc: "TMC-OT-Pre-Warn melden", params: false },
  { code: "M912", desc: "TMC-OT-Pre-Warn löschen", params: false },
  { code: "M913", desc: "Hybrid-Threshold-Speed setzen", params: true, example: "X50 Y50" },
  { code: "M914", desc: "Sensorless-Homing-Empfindlichkeit", params: true, example: "X5" },
  { code: "M915", desc: "TMC Z-Achsen-Kalibrierung", params: true, example: "Z" },
  { code: "M916", desc: "L6474 Thermal-Warn-Test", params: true, example: "" },
  { code: "M917", desc: "L6474 Überstrom-Warn-Test", params: true, example: "" },
  { code: "M918", desc: "L6474 Geschwindigkeits-Warn-Test", params: true, example: "" },
  { code: "M919", desc: "TMC-Chopper-Timing", params: true, example: "X1" },
  { code: "M920", desc: "TMC-Homing-Strom", params: true, example: "X600" },
  { code: "M928", desc: "Serielle Eingabe auf SD loggen", params: true, example: "log.txt" },
  { code: "M951", desc: "Magnetic Parking Extruder-Settings", params: true, example: "" },
  { code: "M993", desc: "Flash-Konfig auf SD sichern", params: false },
  { code: "M994", desc: "Flash von SD wiederherstellen", params: false },
  { code: "M995", desc: "Touchscreen kalibrieren", params: false },
  { code: "M997", desc: "Firmware-Update ausführen", params: false },
  { code: "M999", desc: "STOP / Neustart in Running-Status", params: false },

  // ----- TOOL CODES -----
  { code: "T0", desc: "Tool/Extruder 0 wählen", params: false },
  { code: "T1", desc: "Tool/Extruder 1 wählen", params: false },
  { code: "T2", desc: "Tool/Extruder 2 wählen", params: false },
  { code: "T3", desc: "Tool/Extruder 3 wählen", params: false },
  { code: "T4", desc: "Tool/Extruder 4 wählen", params: false },
  { code: "T5", desc: "Tool/Extruder 5 wählen", params: false },
  { code: "T6", desc: "Tool/Extruder 6 wählen", params: false },
  { code: "T7", desc: "Tool/Extruder 7 wählen", params: false }
];
